### ISSUE TITLE
Meridian: Claim FIL

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/desktop#877]
_Start this issue ASAP, to kick off the design work_

```[tasklist]
### Tasks
- [ ] Write UI spec
- [ ] Visualize unclaimed rewards
- [ ] Ability to claim FIL, with confirmation
- [ ] Backend: Discovery of rewards available to claim
```

**Comment by juliangruber** [comment]
We moved to a push model for payments
