### ISSUE TITLE
Add 0x wallet

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/desktop#994]
Either switch from the f1 to a 0x wallet, or replace it. We need the 0x address for easy integration with smart contracts.

Slack discussions:
- https://filecoinproject.slack.com/archives/C03PQG6UT2B/p1695727060317549
```[tasklist]
### Tasks
- [x] Switch to eth stack
- [x] Display f4 address
- [x] Transfer funds to 0x address
- [x] Transfer funds to f4 address
- [x] Transfer funds to f1 address (FilForwarder)
```

**Comment by patrickwoodhead** [comment]
Ship 0x and f4 this week, f1 afterwards
